require: rubocop-rails

AllCops:
  Exclude:
    - "config/initializers/*"
    - "bin/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 190

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 40

Style/Documentation:
  Enabled: false