dist: trusty
addons:
  chrome: stable
deploy:
  provider: heroku
  app: 'lunchorderingsaas'
  api_key:
    secure: '395b988b-aac0-47fc-88ad-0b8544b6aefb'
language: ruby
rvm:
  - 2.6.3
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  - bundle exec rake assets:precompile
  - sudo service postgresql start
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec